# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '584e0c63-2d05-43d0-8481-4eb9e773db66'
  containerRegistry: 'deltak8s.azurecr.io'
  imageRepositoryClient: 'deltaxisclient'
  dockerfilePathClient: '$(Build.SourcesDirectory)/client/Dockerfile'
  imageRepositoryWorker: 'deltaxisworker'
  dockerfilePathWorker: '$(Build.SourcesDirectory)/worker/Dockerfile'
  imageRepositoryServer: 'deltaxisserver'
  dockerfilePathServer: '$(Build.SourcesDirectory)/server/Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build_Client
    displayName: Build Client
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/manifests/'
        artifact: '_manifests'
        publishLocation: 'pipeline'